main:
    expt_name: 'jumbled3same2jumbvariable'
    data_dir: '/content/drive/MyDrive/Graph/data'
    dir: '/content/drive/MyDrive/Graph/'
    vocab_file: 'google-10000-english-no-swears.txt'
    do_env_setup : 0
    do_training : 1
    run_name: 'supreme supreme euro euro' #'supreme word_pred Taskmaster euro movie'
    jumbled_run_flags: ' 0  1 1 0 '
    fed_algorithm: 'apfl gapfl papfl' #gapfl,fedavg,independent
    NUM_CLIENTS: 4
    degree: 3
    init_alpha: 0.5
    num_rounds: 1502
    tau: 10
    batch_size: 128
    max_seq_len: 40
    num_lstm_layers: 1
    hid_size: 300
    dropout: 0.1
    learning_rate: 0.01
    min_learning_rate: 0.0001
    weight_decay_factor: 0.5
    epochs: 1
    steps_for_validation: 10
    match: None
    use_cuda: 1
    device_id: 0 
    clients: 'reddit'
    alpha_lr: 1.0
    load_model: 0
    load_model_file: 0
    jumbled: 'jumbled_8'#jumbled_8
    save_model: 0
    adaptive_alpha: 1