main:
    dir: 'D:\iisc\FL\graph-federated-learning\'
    vocab_file: 'google-10000-english-no-swears.txt'
    do_env_setup : 0
    do_training : 1
    fed_algorithm: 'papfl' #gapfl,fedavg,independent
    NUM_CLIENTS: 5
    init_alpha: 0.5
    num_rounds: 2
    tau: 10
    batch_size: 128
    max_seq_len: 40
    num_lstm_layers: 1
    hid_size: 300
    dropout: 0.1
    learning_rate: 0.01
    min_learning_rate: 0.0001
    weight_decay_factor: 0.5
    run_name: 'supreme word_pred Taskmaster euro movie'
    epochs: 1
    steps_for_validation: 10
    match: None
    use_cuda: 1
    device_id: 0 
    clients: 'reddit'
    alpha_lr: 1.0
    load_model: 0
    load_model_file: 0

    